import type { AppState } from "@/lib/types";

const now = Date.now();
const minutesAgo = (minutes: number) =>
  new Date(now - minutes * 60_000).toISOString();

export const DEMO_PASSWORD = "demo123";

export const initialState: AppState = {
  session: false,
  pinUnlocked: false,
  user: {
    id: "usr_modest",
    name: "Modest Tatoh",
    lbpayId: "modest",
    email: "modest@lbpay.cm",
    phone: "670112233",
    avatar: "/illustrations/avatar-modest.png",
    kycStatus: "verified",
  },
  balance: 125_500,
  environment: "sandbox",
  toast: null,
  transactions: [
    {
      id: "TXN-892A-4B",
      kind: "receive",
      amount: 45_000,
      fee: 0,
      status: "success",
      method: "mtn",
      counterparty: "Marie K.",
      note: "Python course deposit",
      createdAt: minutesAgo(90),
    },
    {
      id: "TXN-711C-9F",
      kind: "cross_network",
      amount: 20_000,
      fee: 300,
      status: "success",
      method: "orange",
      counterparty: "677445566",
      note: "MTN → Orange",
      createdAt: minutesAgo(180),
    },
    {
      id: "TXN-334D-2E",
      kind: "airtime",
      amount: 1_000,
      fee: 0,
      status: "success",
      method: "wallet",
      counterparty: "MTN 670112233",
      createdAt: minutesAgo(400),
    },
    {
      id: "TXN-102B-5A",
      kind: "deposit",
      amount: 50_000,
      fee: 0,
      status: "success",
      method: "mtn",
      counterparty: "MTN Mobile Money",
      createdAt: minutesAgo(900),
    },
    {
      id: "TXN-551E-8C",
      kind: "send",
      amount: 10_000,
      fee: 0,
      status: "success",
      method: "wallet",
      counterparty: "@kossi",
      createdAt: minutesAgo(1400),
    },
    {
      id: "TXN-220F-1A",
      kind: "collection",
      amount: 120_000,
      fee: 1_800,
      status: "success",
      method: "orange",
      counterparty: "marie.k@company.cm",
      createdAt: minutesAgo(1600),
    },
    {
      id: "TXN-019A-7D",
      kind: "collection",
      amount: 15_500,
      fee: 0,
      status: "failed",
      method: "card",
      counterparty: "guest_8829",
      createdAt: minutesAgo(1800),
    },
  ],
  beneficiaries: [
    { id: "ben_1", name: "Marie Kamga", phone: "677445566", network: "orange" },
    { id: "ben_2", name: "Jean Fotso", phone: "650987654", network: "mtn" },
    { id: "ben_3", name: "Kossi Mensah", lbpayId: "kossi" },
  ],
  links: [
    {
      id: "lnk_python",
      slug: "python-course",
      title: "Pay for Python Course",
      amount: 25_000,
      status: "active",
      collected: 175_000,
      payments: 7,
      createdAt: minutesAgo(10_000),
    },
    {
      id: "lnk_invoice",
      slug: "invoice-892",
      title: "Invoice #892",
      amount: 12_500,
      status: "active",
      collected: 12_500,
      payments: 1,
      createdAt: minutesAgo(2_000),
    },
  ],
  requests: [
    {
      id: "req_modest",
      toName: "Marie Kamga",
      toHandle: "marie",
      amount: 50_000,
      message: "For this month's rent split",
      status: "pending",
      createdAt: minutesAgo(40),
    },
  ],
  business: {
    name: "Python Mastery Institute",
    revenue: 12_450_000,
    activeLinks: 42,
    nextPayout: 2_100_000,
    nextPayoutAt: "Tomorrow, 09:00",
    settlementStatus: "clear",
  },
  apiKeys: [
    {
      env: "sandbox",
      publicKey: "pk_test_51Nx8h42lbpaydemo",
      secretKeyMasked: "sk_test_••••••••••••9x2a",
    },
    {
      env: "live",
      publicKey: "pk_live_8h427b19lbpay",
      secretKeyMasked: "sk_live_••••••••••••9x2a",
    },
  ],
  logs: [
    {
      id: "log_1",
      status: 200,
      method: "POST",
      path: "/v1/payments",
      createdAt: minutesAgo(3),
    },
    {
      id: "log_2",
      status: 200,
      method: "GET",
      path: "/v1/balance",
      createdAt: minutesAgo(8),
    },
    {
      id: "log_3",
      status: 400,
      method: "POST",
      path: "/v1/payments",
      createdAt: minutesAgo(18),
    },
    {
      id: "log_4",
      status: 200,
      method: "POST",
      path: "/v1/payouts",
      createdAt: minutesAgo(30),
    },
    {
      id: "log_5",
      status: 200,
      method: "POST",
      path: "/v1/customers",
      createdAt: minutesAgo(55),
    },
  ],
  webhooks: [
    {
      id: "wh_1",
      url: "https://intellex.cm/webhooks/lbpay",
      events: ["payment.succeeded", "payment.failed", "payout.paid"],
      status: "active",
    },
  ],
  payouts: [
    {
      id: "po_1",
      amount: 50_000,
      phone: "650987654",
      network: "mtn",
      status: "success",
      createdAt: minutesAgo(120),
    },
    {
      id: "po_2",
      amount: 25_000,
      phone: "677445566",
      network: "orange",
      status: "pending",
      createdAt: minutesAgo(20),
    },
  ],
  subscriptions: [
    {
      id: "sub_premium",
      name: "Premium",
      amount: 5_000,
      interval: "monthly",
      subscribers: 128,
      status: "active",
    },
    {
      id: "sub_class",
      name: "Python Bootcamp",
      amount: 25_000,
      interval: "monthly",
      subscribers: 42,
      status: "active",
    },
  ],
};
